name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master  # When you push to main branch, deploy will trigger

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: ./src

      - name: Build project
        run: npm run build
        working-directory: ./src

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/build
